services:
  - type: web
    name: hrm-leaves
    env: python
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn hrm_leaves_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hrm_leaves_backend.settings
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
